# name: CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Install uv
#       uses: astral-sh/setup-uv@v7
#       with:
#         version: "latest"
#         enable-cache: true
#         cache-dependency-glob: "uv.lock"

#     - name: Ensure Makefile available
#       run: make --version

#     - name: Run Lint
#       run: make lint

#     - name: Run Typecheck
#       run: make typecheck

#     - name: Run Tests
#       run: make test
